# Generated by Django 4.1.7 on 2023-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='list of categories'),
        ),
    ]
